# Generated by Django 4.0.1 on 2022-01-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(upload_to='media/uploads/<django.db.models.fields.CharField>'),
        ),
    ]
